/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminEnquiry { 'listingTitle' : string, 'enquiry' : Enquiry }
export interface AdminListingSummary {
  'listing' : Listing,
  'enquiryCount' : bigint,
}
export interface AdminPayment {
  'customerName' : string,
  'customerEmail' : string,
  'payment' : Payment,
}
export interface Banner {
  'id' : BannerId,
  'title' : string,
  'linkUrl' : string,
  'sortOrder' : bigint,
  'createdAt' : Timestamp,
  'enabled' : boolean,
  'updatedAt' : Timestamp,
  'image' : [] | [Photo],
  'subtitle' : string,
}
export type BannerId = bigint;
export interface BannerInput {
  'title' : string,
  'linkUrl' : string,
  'sortOrder' : bigint,
  'enabled' : boolean,
  'image' : [] | [Photo],
  'subtitle' : string,
}
export interface Category {
  'id' : CategoryId,
  'sortOrder' : bigint,
  'name' : string,
  'slug' : string,
  'description' : string,
  'enabled' : boolean,
}
export type CategoryId = bigint;
export interface CategoryInput {
  'sortOrder' : bigint,
  'name' : string,
  'slug' : string,
  'description' : string,
  'enabled' : boolean,
}
export interface Cell { 'value' : Value, 'name' : string }
export interface ChatbotEntry {
  'id' : ChatbotEntryId,
  'question' : string,
  'sortOrder' : bigint,
  'answer' : string,
  'enabled' : boolean,
  'keywords' : Array<string>,
  'updatedAt' : Timestamp,
}
export type ChatbotEntryId = bigint;
export interface ChatbotEntryInput {
  'question' : string,
  'sortOrder' : bigint,
  'answer' : string,
  'enabled' : boolean,
  'keywords' : Array<string>,
}
export type ContentError = { 'notAuthorized' : null } |
  { 'notFound' : bigint } |
  { 'bannerLimitReached' : bigint };
export interface Customer {
  'principal' : CustomerId,
  'blocked' : boolean,
  'mobileVerification' : MobileVerification,
  'name' : string,
  'createdAt' : Timestamp,
  'whatsapp' : string,
  'email' : string,
  'updatedAt' : Timestamp,
  'company' : string,
  'address' : string,
  'phone' : string,
  'emailVerification' : EmailVerification,
}
export interface CustomerAccount {
  'customer' : Customer,
  'subscription' : [] | [Subscription],
}
export type CustomerError = { 'notAuthorized' : null } |
  { 'notFound' : CustomerId } |
  { 'invalidCode' : null } |
  { 'alreadyRegistered' : null } |
  { 'notRegistered' : null };
export type CustomerId = Principal;
export interface CustomerProfileInput {
  'name' : string,
  'whatsapp' : string,
  'email' : string,
  'company' : string,
  'address' : string,
  'phone' : string,
}
export type EmailVerification = { 'verified' : null } |
  { 'pending' : null } |
  { 'unverified' : null };
export interface Enquiry {
  'id' : EnquiryId,
  'listingId' : ListingId,
  'name' : string,
  'createdAt' : Timestamp,
  'read' : boolean,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export type EnquiryAdminError = { 'notAuthorized' : null } |
  { 'notFound' : EnquiryId };
export type EnquiryError = { 'listingNotPublished' : ListingId } |
  { 'listingNotFound' : ListingId };
export type EnquiryId = bigint;
export interface EnquiryInput {
  'listingId' : ListingId,
  'name' : string,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface Listing {
  'id' : ListingId,
  'region' : string,
  'title' : string,
  'featured' : boolean,
  'postcode' : string,
  'country' : string,
  'propertyType' : PropertyType,
  'bedrooms' : bigint,
  'owner' : [] | [CustomerId],
  'area' : bigint,
  'city' : string,
  'blocked' : boolean,
  'published' : boolean,
  'createdAt' : Timestamp,
  'description' : string,
  'listingType' : ListingType,
  'updatedAt' : Timestamp,
  'currency' : string,
  'addressLine' : string,
  'bathrooms' : bigint,
  'price' : bigint,
  'photos' : Array<Photo>,
}
export type ListingError = { 'listingLimitReached' : bigint } |
  { 'noActiveSubscription' : null } |
  { 'notAuthorized' : null } |
  { 'imageLimitReached' : bigint } |
  { 'notFound' : ListingId };
export interface ListingFilter {
  'propertyType' : [] | [PropertyType],
  'minBedrooms' : [] | [bigint],
  'maxPrice' : [] | [bigint],
  'listingType' : [] | [ListingType],
  'keyword' : [] | [string],
  'minPrice' : [] | [bigint],
  'location' : [] | [string],
}
export type ListingId = bigint;
export interface ListingInput {
  'region' : string,
  'title' : string,
  'postcode' : string,
  'country' : string,
  'propertyType' : PropertyType,
  'bedrooms' : bigint,
  'area' : bigint,
  'city' : string,
  'description' : string,
  'listingType' : ListingType,
  'currency' : string,
  'addressLine' : string,
  'bathrooms' : bigint,
  'price' : bigint,
  'photos' : Array<Photo>,
}
export type ListingType = { 'rent' : null } |
  { 'sale' : null };
export interface ListingUpdate {
  'region' : [] | [string],
  'title' : [] | [string],
  'postcode' : [] | [string],
  'country' : [] | [string],
  'propertyType' : [] | [PropertyType],
  'bedrooms' : [] | [bigint],
  'area' : [] | [bigint],
  'city' : [] | [string],
  'description' : [] | [string],
  'listingType' : [] | [ListingType],
  'currency' : [] | [string],
  'addressLine' : [] | [string],
  'bathrooms' : [] | [bigint],
  'price' : [] | [bigint],
  'photos' : [] | [Array<Photo>],
}
export type MobileVerification = { 'pendingReview' : null } |
  { 'notSubmitted' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Payment {
  'id' : PaymentId,
  'status' : PaymentStatus,
  'customer' : CustomerId,
  'planId' : PlanId,
  'reference' : string,
  'submittedAt' : Timestamp,
  'reviewedAt' : [] | [Timestamp],
  'periodEnd' : [] | [Timestamp],
  'periodStart' : [] | [Timestamp],
  'amount' : bigint,
  'planName' : string,
}
export type PaymentError = { 'planNotFound' : PlanId } |
  { 'listingLimitReached' : bigint } |
  { 'noActiveSubscription' : null } |
  { 'notAuthorized' : null } |
  { 'imageLimitReached' : bigint } |
  { 'paymentNotFound' : PaymentId } |
  { 'notRegistered' : null };
export type PaymentId = bigint;
export type PaymentStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'confirmed' : null };
export interface Photo { 'blob' : Uint8Array, 'filename' : string }
export interface Plan {
  'id' : PlanId,
  'features' : Array<string>,
  'active' : boolean,
  'sortOrder' : bigint,
  'name' : string,
  'listingAllowance' : [] | [bigint],
  'billingPeriod' : string,
  'imageAllowance' : [] | [bigint],
  'price' : bigint,
}
export type PlanId = bigint;
export interface PlanInput {
  'features' : Array<string>,
  'active' : boolean,
  'sortOrder' : bigint,
  'name' : string,
  'listingAllowance' : [] | [bigint],
  'billingPeriod' : string,
  'imageAllowance' : [] | [bigint],
  'price' : bigint,
}
export type PropertyType = { 'commercial' : null } |
  { 'house' : null } |
  { 'other' : null } |
  { 'land' : null } |
  { 'condo' : null } |
  { 'apartment' : null } |
  { 'townhouse' : null };
export type Result = { 'ok' : Customer } |
  { 'err' : CustomerError };
export type Result_1 = { 'ok' : Listing } |
  { 'err' : ListingError };
export type Result_10 = { 'ok' : Enquiry } |
  { 'err' : EnquiryAdminError };
export type Result_11 = { 'ok' : null } |
  { 'err' : PaymentError };
export type Result_12 = { 'ok' : null } |
  { 'err' : ContentError };
export type Result_13 = { 'ok' : null } |
  { 'err' : Error };
export type Result_2 = { 'ok' : Payment } |
  { 'err' : PaymentError };
export type Result_3 = { 'ok' : Enquiry } |
  { 'err' : EnquiryError };
export type Result_4 = { 'ok' : null } |
  { 'err' : CustomerError };
export type Result_5 = { 'ok' : null } |
  { 'err' : ListingError };
export type Result_6 = { 'ok' : Plan } |
  { 'err' : PaymentError };
export type Result_7 = { 'ok' : ChatbotEntry } |
  { 'err' : ContentError };
export type Result_8 = { 'ok' : Category } |
  { 'err' : ContentError };
export type Result_9 = { 'ok' : Banner } |
  { 'err' : ContentError };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export interface Subscription {
  'status' : SubscriptionStatus,
  'startedAt' : Timestamp,
  'expiresAt' : Timestamp,
  'planId' : PlanId,
  'billingPeriod' : string,
  'renewedAt' : [] | [Timestamp],
  'price' : bigint,
  'planName' : string,
}
export type SubscriptionStatus = { 'active' : null } |
  { 'expired' : null };
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result_13>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  /**
   * / Appends photos to one of the calling customer's own listings, enforcing
   * / the plan's image allowance.
   */
  'addMyListingPhotos' : ActorMethod<[ListingId, Array<Photo>], Result_1>,
  /**
   * / Appends uploaded photos to a listing. Admin only.
   */
  'adminAddListingPhotos' : ActorMethod<[ListingId, Array<Photo>], Result_1>,
  /**
   * / Confirms a submitted payment and activates or renews the subscription.
   * / Admin only.
   */
  'adminConfirmPayment' : ActorMethod<[PaymentId], Result_2>,
  /**
   * / Creates a banner. Admin only.
   */
  'adminCreateBanner' : ActorMethod<[BannerInput], Result_9>,
  /**
   * / Creates a category. Admin only.
   */
  'adminCreateCategory' : ActorMethod<[CategoryInput], Result_8>,
  /**
   * / Creates a chatbot entry. Admin only.
   */
  'adminCreateChatbotEntry' : ActorMethod<[ChatbotEntryInput], Result_7>,
  /**
   * / Creates a listing. Admin only.
   */
  'adminCreateListing' : ActorMethod<[ListingInput], Result_1>,
  /**
   * / Creates a plan. Admin only.
   */
  'adminCreatePlan' : ActorMethod<[PlanInput], Result_6>,
  /**
   * / Deletes a banner. Admin only.
   */
  'adminDeleteBanner' : ActorMethod<[BannerId], Result_12>,
  /**
   * / Deletes a category. Admin only.
   */
  'adminDeleteCategory' : ActorMethod<[CategoryId], Result_12>,
  /**
   * / Deletes a chatbot entry. Admin only.
   */
  'adminDeleteChatbotEntry' : ActorMethod<[ChatbotEntryId], Result_12>,
  /**
   * / Deletes an enquiry. Admin only.
   */
  'adminDeleteEnquiry' : ActorMethod<[EnquiryId], Result_5>,
  /**
   * / Deletes a listing and its enquiries. Admin only.
   */
  'adminDeleteListing' : ActorMethod<[ListingId], Result_5>,
  /**
   * / Deletes a plan. Admin only.
   */
  'adminDeletePlan' : ActorMethod<[PlanId], Result_11>,
  /**
   * / Returns a single listing regardless of published state. Admin only.
   */
  'adminGetListing' : ActorMethod<[ListingId], [] | [Listing]>,
  /**
   * / Returns a customer's subscription. Admin only.
   */
  'adminGetSubscription' : ActorMethod<[CustomerId], [] | [Subscription]>,
  /**
   * / Returns every banner, enabled or not. Admin only.
   */
  'adminListBanners' : ActorMethod<[], Array<Banner>>,
  /**
   * / Returns every category, enabled or not. Admin only.
   */
  'adminListCategories' : ActorMethod<[], Array<Category>>,
  /**
   * / Returns every chatbot entry, enabled or not. Admin only.
   */
  'adminListChatbotEntries' : ActorMethod<[], Array<ChatbotEntry>>,
  /**
   * / Returns every customer account. Admin only.
   */
  'adminListCustomers' : ActorMethod<[], Array<CustomerAccount>>,
  /**
   * / Returns every enquiry, newest first, each with its listing title. Admin only.
   */
  'adminListEnquiries' : ActorMethod<[], Array<AdminEnquiry>>,
  /**
   * / Returns every listing with its enquiry count, newest first. Admin only.
   */
  'adminListListings' : ActorMethod<[], Array<AdminListingSummary>>,
  /**
   * / Returns every payment with its customer's details. Admin only.
   */
  'adminListPayments' : ActorMethod<[], Array<AdminPayment>>,
  /**
   * / Returns every plan, active or not. Admin only.
   */
  'adminListPlans' : ActorMethod<[], Array<Plan>>,
  /**
   * / Rejects a submitted payment. Admin only.
   */
  'adminRejectPayment' : ActorMethod<[PaymentId], Result_2>,
  /**
   * / Removes the photo at `index` from a listing. Admin only.
   */
  'adminRemoveListingPhoto' : ActorMethod<[ListingId, bigint], Result_1>,
  /**
   * / Moves a banner to a new slider position. Admin only.
   */
  'adminReorderBanner' : ActorMethod<[BannerId, bigint], Result_9>,
  /**
   * / Enables or disables a banner. Admin only.
   */
  'adminSetBannerEnabled' : ActorMethod<[BannerId, boolean], Result_9>,
  /**
   * / Blocks or unblocks a customer account. Admin only.
   */
  'adminSetCustomerBlocked' : ActorMethod<[CustomerId, boolean], Result>,
  /**
   * / Sets the read flag on an enquiry. Admin only.
   */
  'adminSetEnquiryRead' : ActorMethod<[EnquiryId, boolean], Result_10>,
  /**
   * / Blocks or unblocks a listing. Admin only.
   */
  'adminSetListingBlocked' : ActorMethod<[ListingId, boolean], Result_1>,
  /**
   * / Features or unfeatures a listing. Admin only.
   */
  'adminSetListingFeatured' : ActorMethod<[ListingId, boolean], Result_1>,
  /**
   * / Publishes or unpublishes a listing. Admin only.
   */
  'adminSetListingPublished' : ActorMethod<[ListingId, boolean], Result_1>,
  /**
   * / Approves or rejects a customer's submitted mobile number. Admin only.
   */
  'adminSetMobileVerification' : ActorMethod<
    [CustomerId, MobileVerification],
    Result
  >,
  /**
   * / Applies a full edit to a banner. Admin only.
   */
  'adminUpdateBanner' : ActorMethod<[BannerId, BannerInput], Result_9>,
  /**
   * / Applies a full edit to a category. Admin only.
   */
  'adminUpdateCategory' : ActorMethod<[CategoryId, CategoryInput], Result_8>,
  /**
   * / Applies a full edit to a chatbot entry. Admin only.
   */
  'adminUpdateChatbotEntry' : ActorMethod<
    [ChatbotEntryId, ChatbotEntryInput],
    Result_7
  >,
  /**
   * / Applies a partial update to a listing. Admin only.
   */
  'adminUpdateListing' : ActorMethod<[ListingId, ListingUpdate], Result_1>,
  /**
   * / Applies a full edit to a plan. Admin only.
   */
  'adminUpdatePlan' : ActorMethod<[PlanId, PlanInput], Result_6>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Confirms the email verification code.
   */
  'confirmEmailVerification' : ActorMethod<[string], Result>,
  /**
   * / Creates a listing owned by the calling customer. Requires an active
   * / subscription and enforces the plan's listing and image allowances.
   */
  'createMyListing' : ActorMethod<[ListingInput], Result_1>,
  /**
   * / Deletes one of the calling customer's own listings.
   */
  'deleteMyListing' : ActorMethod<[ListingId], Result_5>,
  'execute' : ActorMethod<[string], Result__1>,
  /**
   * / Returns the backend API reference as Markdown.
   */
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Returns a single published listing, or `null` when it does not exist or is
   * / not published.
   */
  'getListing' : ActorMethod<[ListingId], [] | [Listing]>,
  /**
   * / Returns the calling customer's account with its subscription summary.
   */
  'getMyAccount' : ActorMethod<[], [] | [CustomerAccount]>,
  /**
   * / Returns one of the calling customer's own listings, or `null`.
   */
  'getMyListing' : ActorMethod<[ListingId], [] | [Listing]>,
  /**
   * / Returns the calling customer's own listings, newest first.
   */
  'getMyListings' : ActorMethod<[], Array<Listing>>,
  /**
   * / Returns the calling customer's payment history, newest first.
   */
  'getMyPayments' : ActorMethod<[], Array<Payment>>,
  /**
   * / Returns the calling customer's subscription, or `null` when none exists.
   */
  'getMySubscription' : ActorMethod<[], [] | [Subscription]>,
  /**
   * / Returns a single plan, or `null` when it does not exist.
   */
  'getPlan' : ActorMethod<[PlanId], [] | [Plan]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Returns the enabled homepage banners ordered by `sortOrder`.
   */
  'listBanners' : ActorMethod<[], Array<Banner>>,
  /**
   * / Returns the enabled advertising categories ordered by `sortOrder`.
   */
  'listCategories' : ActorMethod<[], Array<Category>>,
  /**
   * / Returns the enabled help chatbot entries ordered by `sortOrder`.
   */
  'listChatbotEntries' : ActorMethod<[], Array<ChatbotEntry>>,
  /**
   * / Returns the featured published listings, newest first.
   */
  'listFeaturedListings' : ActorMethod<[], Array<Listing>>,
  /**
   * / Returns every active plan ordered by `sortOrder`.
   */
  'listPlans' : ActorMethod<[], Array<Plan>>,
  /**
   * / Returns every published listing, newest first.
   */
  'listPublishedListings' : ActorMethod<[], Array<Listing>>,
  /**
   * / Registers the calling principal as a customer.
   */
  'registerCustomer' : ActorMethod<[CustomerProfileInput], Result>,
  /**
   * / Removes the photo at `index` from one of the calling customer's own
   * / listings.
   */
  'removeMyListingPhoto' : ActorMethod<[ListingId, bigint], Result_1>,
  /**
   * / Requests an email verification code for the supplied address.
   */
  'requestEmailVerification' : ActorMethod<[string], Result_4>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Returns published listings matching the supplied filters, newest first.
   */
  'searchListings' : ActorMethod<[ListingFilter], Array<Listing>>,
  /**
   * / Submits an enquiry against a published listing.
   */
  'submitEnquiry' : ActorMethod<[EnquiryInput], Result_3>,
  /**
   * / Records a mobile number for admin review. No SMS provider is configured.
   */
  'submitMobileNumber' : ActorMethod<[string], Result>,
  /**
   * / Submits a payment reference for a plan. The payment stays pending until an
   * / admin confirms it.
   */
  'submitPayment' : ActorMethod<[PlanId, string], Result_2>,
  /**
   * / Applies a partial update to one of the calling customer's own listings.
   */
  'updateMyListing' : ActorMethod<[ListingId, ListingUpdate], Result_1>,
  /**
   * / Updates the calling customer's profile.
   */
  'updateMyProfile' : ActorMethod<[CustomerProfileInput], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];