/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result_13 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const ListingId = IDL.Nat;
export const Photo = IDL.Record({
  'blob' : IDL.Vec(IDL.Nat8),
  'filename' : IDL.Text,
});
export const PropertyType = IDL.Variant({
  'commercial' : IDL.Null,
  'house' : IDL.Null,
  'other' : IDL.Null,
  'land' : IDL.Null,
  'condo' : IDL.Null,
  'apartment' : IDL.Null,
  'townhouse' : IDL.Null,
});
export const CustomerId = IDL.Principal;
export const Timestamp = IDL.Int;
export const ListingType = IDL.Variant({
  'rent' : IDL.Null,
  'sale' : IDL.Null,
});
export const Listing = IDL.Record({
  'id' : ListingId,
  'region' : IDL.Text,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'postcode' : IDL.Text,
  'country' : IDL.Text,
  'propertyType' : PropertyType,
  'bedrooms' : IDL.Nat,
  'owner' : IDL.Opt(CustomerId),
  'area' : IDL.Nat,
  'city' : IDL.Text,
  'blocked' : IDL.Bool,
  'published' : IDL.Bool,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'listingType' : ListingType,
  'updatedAt' : Timestamp,
  'currency' : IDL.Text,
  'addressLine' : IDL.Text,
  'bathrooms' : IDL.Nat,
  'price' : IDL.Nat,
  'photos' : IDL.Vec(Photo),
});
export const ListingError = IDL.Variant({
  'listingLimitReached' : IDL.Nat,
  'noActiveSubscription' : IDL.Null,
  'notAuthorized' : IDL.Null,
  'imageLimitReached' : IDL.Nat,
  'notFound' : ListingId,
});
export const Result_1 = IDL.Variant({ 'ok' : Listing, 'err' : ListingError });
export const PaymentId = IDL.Nat;
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const PlanId = IDL.Nat;
export const Payment = IDL.Record({
  'id' : PaymentId,
  'status' : PaymentStatus,
  'customer' : CustomerId,
  'planId' : PlanId,
  'reference' : IDL.Text,
  'submittedAt' : Timestamp,
  'reviewedAt' : IDL.Opt(Timestamp),
  'periodEnd' : IDL.Opt(Timestamp),
  'periodStart' : IDL.Opt(Timestamp),
  'amount' : IDL.Nat,
  'planName' : IDL.Text,
});
export const PaymentError = IDL.Variant({
  'planNotFound' : PlanId,
  'listingLimitReached' : IDL.Nat,
  'noActiveSubscription' : IDL.Null,
  'notAuthorized' : IDL.Null,
  'imageLimitReached' : IDL.Nat,
  'paymentNotFound' : PaymentId,
  'notRegistered' : IDL.Null,
});
export const Result_2 = IDL.Variant({ 'ok' : Payment, 'err' : PaymentError });
export const BannerInput = IDL.Record({
  'title' : IDL.Text,
  'linkUrl' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'enabled' : IDL.Bool,
  'image' : IDL.Opt(Photo),
  'subtitle' : IDL.Text,
});
export const BannerId = IDL.Nat;
export const Banner = IDL.Record({
  'id' : BannerId,
  'title' : IDL.Text,
  'linkUrl' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'createdAt' : Timestamp,
  'enabled' : IDL.Bool,
  'updatedAt' : Timestamp,
  'image' : IDL.Opt(Photo),
  'subtitle' : IDL.Text,
});
export const ContentError = IDL.Variant({
  'notAuthorized' : IDL.Null,
  'notFound' : IDL.Nat,
  'bannerLimitReached' : IDL.Nat,
});
export const Result_9 = IDL.Variant({ 'ok' : Banner, 'err' : ContentError });
export const CategoryInput = IDL.Record({
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'description' : IDL.Text,
  'enabled' : IDL.Bool,
});
export const CategoryId = IDL.Nat;
export const Category = IDL.Record({
  'id' : CategoryId,
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'description' : IDL.Text,
  'enabled' : IDL.Bool,
});
export const Result_8 = IDL.Variant({ 'ok' : Category, 'err' : ContentError });
export const ChatbotEntryInput = IDL.Record({
  'question' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'answer' : IDL.Text,
  'enabled' : IDL.Bool,
  'keywords' : IDL.Vec(IDL.Text),
});
export const ChatbotEntryId = IDL.Nat;
export const ChatbotEntry = IDL.Record({
  'id' : ChatbotEntryId,
  'question' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'answer' : IDL.Text,
  'enabled' : IDL.Bool,
  'keywords' : IDL.Vec(IDL.Text),
  'updatedAt' : Timestamp,
});
export const Result_7 = IDL.Variant({
  'ok' : ChatbotEntry,
  'err' : ContentError,
});
export const ListingInput = IDL.Record({
  'region' : IDL.Text,
  'title' : IDL.Text,
  'postcode' : IDL.Text,
  'country' : IDL.Text,
  'propertyType' : PropertyType,
  'bedrooms' : IDL.Nat,
  'area' : IDL.Nat,
  'city' : IDL.Text,
  'description' : IDL.Text,
  'listingType' : ListingType,
  'currency' : IDL.Text,
  'addressLine' : IDL.Text,
  'bathrooms' : IDL.Nat,
  'price' : IDL.Nat,
  'photos' : IDL.Vec(Photo),
});
export const PlanInput = IDL.Record({
  'features' : IDL.Vec(IDL.Text),
  'active' : IDL.Bool,
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
  'listingAllowance' : IDL.Opt(IDL.Nat),
  'billingPeriod' : IDL.Text,
  'imageAllowance' : IDL.Opt(IDL.Nat),
  'price' : IDL.Nat,
});
export const Plan = IDL.Record({
  'id' : PlanId,
  'features' : IDL.Vec(IDL.Text),
  'active' : IDL.Bool,
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
  'listingAllowance' : IDL.Opt(IDL.Nat),
  'billingPeriod' : IDL.Text,
  'imageAllowance' : IDL.Opt(IDL.Nat),
  'price' : IDL.Nat,
});
export const Result_6 = IDL.Variant({ 'ok' : Plan, 'err' : PaymentError });
export const Result_12 = IDL.Variant({ 'ok' : IDL.Null, 'err' : ContentError });
export const EnquiryId = IDL.Nat;
export const Result_5 = IDL.Variant({ 'ok' : IDL.Null, 'err' : ListingError });
export const Result_11 = IDL.Variant({ 'ok' : IDL.Null, 'err' : PaymentError });
export const SubscriptionStatus = IDL.Variant({
  'active' : IDL.Null,
  'expired' : IDL.Null,
});
export const Subscription = IDL.Record({
  'status' : SubscriptionStatus,
  'startedAt' : Timestamp,
  'expiresAt' : Timestamp,
  'planId' : PlanId,
  'billingPeriod' : IDL.Text,
  'renewedAt' : IDL.Opt(Timestamp),
  'price' : IDL.Nat,
  'planName' : IDL.Text,
});
export const MobileVerification = IDL.Variant({
  'pendingReview' : IDL.Null,
  'notSubmitted' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const EmailVerification = IDL.Variant({
  'verified' : IDL.Null,
  'pending' : IDL.Null,
  'unverified' : IDL.Null,
});
export const Customer = IDL.Record({
  'principal' : CustomerId,
  'blocked' : IDL.Bool,
  'mobileVerification' : MobileVerification,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'whatsapp' : IDL.Text,
  'email' : IDL.Text,
  'updatedAt' : Timestamp,
  'company' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'emailVerification' : EmailVerification,
});
export const CustomerAccount = IDL.Record({
  'customer' : Customer,
  'subscription' : IDL.Opt(Subscription),
});
export const Enquiry = IDL.Record({
  'id' : EnquiryId,
  'listingId' : ListingId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'read' : IDL.Bool,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const AdminEnquiry = IDL.Record({
  'listingTitle' : IDL.Text,
  'enquiry' : Enquiry,
});
export const AdminListingSummary = IDL.Record({
  'listing' : Listing,
  'enquiryCount' : IDL.Nat,
});
export const AdminPayment = IDL.Record({
  'customerName' : IDL.Text,
  'customerEmail' : IDL.Text,
  'payment' : Payment,
});
export const CustomerError = IDL.Variant({
  'notAuthorized' : IDL.Null,
  'notFound' : CustomerId,
  'invalidCode' : IDL.Null,
  'alreadyRegistered' : IDL.Null,
  'notRegistered' : IDL.Null,
});
export const Result = IDL.Variant({ 'ok' : Customer, 'err' : CustomerError });
export const EnquiryAdminError = IDL.Variant({
  'notAuthorized' : IDL.Null,
  'notFound' : EnquiryId,
});
export const Result_10 = IDL.Variant({
  'ok' : Enquiry,
  'err' : EnquiryAdminError,
});
export const ListingUpdate = IDL.Record({
  'region' : IDL.Opt(IDL.Text),
  'title' : IDL.Opt(IDL.Text),
  'postcode' : IDL.Opt(IDL.Text),
  'country' : IDL.Opt(IDL.Text),
  'propertyType' : IDL.Opt(PropertyType),
  'bedrooms' : IDL.Opt(IDL.Nat),
  'area' : IDL.Opt(IDL.Nat),
  'city' : IDL.Opt(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'listingType' : IDL.Opt(ListingType),
  'currency' : IDL.Opt(IDL.Text),
  'addressLine' : IDL.Opt(IDL.Text),
  'bathrooms' : IDL.Opt(IDL.Nat),
  'price' : IDL.Opt(IDL.Nat),
  'photos' : IDL.Opt(IDL.Vec(Photo)),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result__1 = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const CustomerProfileInput = IDL.Record({
  'name' : IDL.Text,
  'whatsapp' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Result_4 = IDL.Variant({ 'ok' : IDL.Null, 'err' : CustomerError });
export const ListingFilter = IDL.Record({
  'propertyType' : IDL.Opt(PropertyType),
  'minBedrooms' : IDL.Opt(IDL.Nat),
  'maxPrice' : IDL.Opt(IDL.Nat),
  'listingType' : IDL.Opt(ListingType),
  'keyword' : IDL.Opt(IDL.Text),
  'minPrice' : IDL.Opt(IDL.Nat),
  'location' : IDL.Opt(IDL.Text),
});
export const EnquiryInput = IDL.Record({
  'listingId' : ListingId,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const EnquiryError = IDL.Variant({
  'listingNotPublished' : ListingId,
  'listingNotFound' : ListingId,
});
export const Result_3 = IDL.Variant({ 'ok' : Enquiry, 'err' : EnquiryError });

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result_13], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addMyListingPhotos' : IDL.Func([ListingId, IDL.Vec(Photo)], [Result_1], []),
  'adminAddListingPhotos' : IDL.Func(
      [ListingId, IDL.Vec(Photo)],
      [Result_1],
      [],
    ),
  'adminConfirmPayment' : IDL.Func([PaymentId], [Result_2], []),
  'adminCreateBanner' : IDL.Func([BannerInput], [Result_9], []),
  'adminCreateCategory' : IDL.Func([CategoryInput], [Result_8], []),
  'adminCreateChatbotEntry' : IDL.Func([ChatbotEntryInput], [Result_7], []),
  'adminCreateListing' : IDL.Func([ListingInput], [Result_1], []),
  'adminCreatePlan' : IDL.Func([PlanInput], [Result_6], []),
  'adminDeleteBanner' : IDL.Func([BannerId], [Result_12], []),
  'adminDeleteCategory' : IDL.Func([CategoryId], [Result_12], []),
  'adminDeleteChatbotEntry' : IDL.Func([ChatbotEntryId], [Result_12], []),
  'adminDeleteEnquiry' : IDL.Func([EnquiryId], [Result_5], []),
  'adminDeleteListing' : IDL.Func([ListingId], [Result_5], []),
  'adminDeletePlan' : IDL.Func([PlanId], [Result_11], []),
  'adminGetListing' : IDL.Func([ListingId], [IDL.Opt(Listing)], ['query']),
  'adminGetSubscription' : IDL.Func(
      [CustomerId],
      [IDL.Opt(Subscription)],
      ['query'],
    ),
  'adminListBanners' : IDL.Func([], [IDL.Vec(Banner)], ['query']),
  'adminListCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'adminListChatbotEntries' : IDL.Func([], [IDL.Vec(ChatbotEntry)], ['query']),
  'adminListCustomers' : IDL.Func([], [IDL.Vec(CustomerAccount)], ['query']),
  'adminListEnquiries' : IDL.Func([], [IDL.Vec(AdminEnquiry)], ['query']),
  'adminListListings' : IDL.Func([], [IDL.Vec(AdminListingSummary)], ['query']),
  'adminListPayments' : IDL.Func([], [IDL.Vec(AdminPayment)], ['query']),
  'adminListPlans' : IDL.Func([], [IDL.Vec(Plan)], ['query']),
  'adminRejectPayment' : IDL.Func([PaymentId], [Result_2], []),
  'adminRemoveListingPhoto' : IDL.Func([ListingId, IDL.Nat], [Result_1], []),
  'adminReorderBanner' : IDL.Func([BannerId, IDL.Nat], [Result_9], []),
  'adminSetBannerEnabled' : IDL.Func([BannerId, IDL.Bool], [Result_9], []),
  'adminSetCustomerBlocked' : IDL.Func([CustomerId, IDL.Bool], [Result], []),
  'adminSetEnquiryRead' : IDL.Func([EnquiryId, IDL.Bool], [Result_10], []),
  'adminSetListingBlocked' : IDL.Func([ListingId, IDL.Bool], [Result_1], []),
  'adminSetListingFeatured' : IDL.Func([ListingId, IDL.Bool], [Result_1], []),
  'adminSetListingPublished' : IDL.Func([ListingId, IDL.Bool], [Result_1], []),
  'adminSetMobileVerification' : IDL.Func(
      [CustomerId, MobileVerification],
      [Result],
      [],
    ),
  'adminUpdateBanner' : IDL.Func([BannerId, BannerInput], [Result_9], []),
  'adminUpdateCategory' : IDL.Func([CategoryId, CategoryInput], [Result_8], []),
  'adminUpdateChatbotEntry' : IDL.Func(
      [ChatbotEntryId, ChatbotEntryInput],
      [Result_7],
      [],
    ),
  'adminUpdateListing' : IDL.Func([ListingId, ListingUpdate], [Result_1], []),
  'adminUpdatePlan' : IDL.Func([PlanId, PlanInput], [Result_6], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'confirmEmailVerification' : IDL.Func([IDL.Text], [Result], []),
  'createMyListing' : IDL.Func([ListingInput], [Result_1], []),
  'deleteMyListing' : IDL.Func([ListingId], [Result_5], []),
  'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getListing' : IDL.Func([ListingId], [IDL.Opt(Listing)], ['query']),
  'getMyAccount' : IDL.Func([], [IDL.Opt(CustomerAccount)], ['query']),
  'getMyListing' : IDL.Func([ListingId], [IDL.Opt(Listing)], ['query']),
  'getMyListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getMyPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getMySubscription' : IDL.Func([], [IDL.Opt(Subscription)], ['query']),
  'getPlan' : IDL.Func([PlanId], [IDL.Opt(Plan)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listBanners' : IDL.Func([], [IDL.Vec(Banner)], ['query']),
  'listCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'listChatbotEntries' : IDL.Func([], [IDL.Vec(ChatbotEntry)], ['query']),
  'listFeaturedListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'listPlans' : IDL.Func([], [IDL.Vec(Plan)], ['query']),
  'listPublishedListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'registerCustomer' : IDL.Func([CustomerProfileInput], [Result], []),
  'removeMyListingPhoto' : IDL.Func([ListingId, IDL.Nat], [Result_1], []),
  'requestEmailVerification' : IDL.Func([IDL.Text], [Result_4], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'searchListings' : IDL.Func([ListingFilter], [IDL.Vec(Listing)], ['query']),
  'submitEnquiry' : IDL.Func([EnquiryInput], [Result_3], []),
  'submitMobileNumber' : IDL.Func([IDL.Text], [Result], []),
  'submitPayment' : IDL.Func([PlanId, IDL.Text], [Result_2], []),
  'updateMyListing' : IDL.Func([ListingId, ListingUpdate], [Result_1], []),
  'updateMyProfile' : IDL.Func([CustomerProfileInput], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result_13 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const ListingId = IDL.Nat;
  const Photo = IDL.Record({
    'blob' : IDL.Vec(IDL.Nat8),
    'filename' : IDL.Text,
  });
  const PropertyType = IDL.Variant({
    'commercial' : IDL.Null,
    'house' : IDL.Null,
    'other' : IDL.Null,
    'land' : IDL.Null,
    'condo' : IDL.Null,
    'apartment' : IDL.Null,
    'townhouse' : IDL.Null,
  });
  const CustomerId = IDL.Principal;
  const Timestamp = IDL.Int;
  const ListingType = IDL.Variant({ 'rent' : IDL.Null, 'sale' : IDL.Null });
  const Listing = IDL.Record({
    'id' : ListingId,
    'region' : IDL.Text,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'postcode' : IDL.Text,
    'country' : IDL.Text,
    'propertyType' : PropertyType,
    'bedrooms' : IDL.Nat,
    'owner' : IDL.Opt(CustomerId),
    'area' : IDL.Nat,
    'city' : IDL.Text,
    'blocked' : IDL.Bool,
    'published' : IDL.Bool,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'listingType' : ListingType,
    'updatedAt' : Timestamp,
    'currency' : IDL.Text,
    'addressLine' : IDL.Text,
    'bathrooms' : IDL.Nat,
    'price' : IDL.Nat,
    'photos' : IDL.Vec(Photo),
  });
  const ListingError = IDL.Variant({
    'listingLimitReached' : IDL.Nat,
    'noActiveSubscription' : IDL.Null,
    'notAuthorized' : IDL.Null,
    'imageLimitReached' : IDL.Nat,
    'notFound' : ListingId,
  });
  const Result_1 = IDL.Variant({ 'ok' : Listing, 'err' : ListingError });
  const PaymentId = IDL.Nat;
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const PlanId = IDL.Nat;
  const Payment = IDL.Record({
    'id' : PaymentId,
    'status' : PaymentStatus,
    'customer' : CustomerId,
    'planId' : PlanId,
    'reference' : IDL.Text,
    'submittedAt' : Timestamp,
    'reviewedAt' : IDL.Opt(Timestamp),
    'periodEnd' : IDL.Opt(Timestamp),
    'periodStart' : IDL.Opt(Timestamp),
    'amount' : IDL.Nat,
    'planName' : IDL.Text,
  });
  const PaymentError = IDL.Variant({
    'planNotFound' : PlanId,
    'listingLimitReached' : IDL.Nat,
    'noActiveSubscription' : IDL.Null,
    'notAuthorized' : IDL.Null,
    'imageLimitReached' : IDL.Nat,
    'paymentNotFound' : PaymentId,
    'notRegistered' : IDL.Null,
  });
  const Result_2 = IDL.Variant({ 'ok' : Payment, 'err' : PaymentError });
  const BannerInput = IDL.Record({
    'title' : IDL.Text,
    'linkUrl' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'enabled' : IDL.Bool,
    'image' : IDL.Opt(Photo),
    'subtitle' : IDL.Text,
  });
  const BannerId = IDL.Nat;
  const Banner = IDL.Record({
    'id' : BannerId,
    'title' : IDL.Text,
    'linkUrl' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'createdAt' : Timestamp,
    'enabled' : IDL.Bool,
    'updatedAt' : Timestamp,
    'image' : IDL.Opt(Photo),
    'subtitle' : IDL.Text,
  });
  const ContentError = IDL.Variant({
    'notAuthorized' : IDL.Null,
    'notFound' : IDL.Nat,
    'bannerLimitReached' : IDL.Nat,
  });
  const Result_9 = IDL.Variant({ 'ok' : Banner, 'err' : ContentError });
  const CategoryInput = IDL.Record({
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'description' : IDL.Text,
    'enabled' : IDL.Bool,
  });
  const CategoryId = IDL.Nat;
  const Category = IDL.Record({
    'id' : CategoryId,
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'description' : IDL.Text,
    'enabled' : IDL.Bool,
  });
  const Result_8 = IDL.Variant({ 'ok' : Category, 'err' : ContentError });
  const ChatbotEntryInput = IDL.Record({
    'question' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'answer' : IDL.Text,
    'enabled' : IDL.Bool,
    'keywords' : IDL.Vec(IDL.Text),
  });
  const ChatbotEntryId = IDL.Nat;
  const ChatbotEntry = IDL.Record({
    'id' : ChatbotEntryId,
    'question' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'answer' : IDL.Text,
    'enabled' : IDL.Bool,
    'keywords' : IDL.Vec(IDL.Text),
    'updatedAt' : Timestamp,
  });
  const Result_7 = IDL.Variant({ 'ok' : ChatbotEntry, 'err' : ContentError });
  const ListingInput = IDL.Record({
    'region' : IDL.Text,
    'title' : IDL.Text,
    'postcode' : IDL.Text,
    'country' : IDL.Text,
    'propertyType' : PropertyType,
    'bedrooms' : IDL.Nat,
    'area' : IDL.Nat,
    'city' : IDL.Text,
    'description' : IDL.Text,
    'listingType' : ListingType,
    'currency' : IDL.Text,
    'addressLine' : IDL.Text,
    'bathrooms' : IDL.Nat,
    'price' : IDL.Nat,
    'photos' : IDL.Vec(Photo),
  });
  const PlanInput = IDL.Record({
    'features' : IDL.Vec(IDL.Text),
    'active' : IDL.Bool,
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
    'listingAllowance' : IDL.Opt(IDL.Nat),
    'billingPeriod' : IDL.Text,
    'imageAllowance' : IDL.Opt(IDL.Nat),
    'price' : IDL.Nat,
  });
  const Plan = IDL.Record({
    'id' : PlanId,
    'features' : IDL.Vec(IDL.Text),
    'active' : IDL.Bool,
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
    'listingAllowance' : IDL.Opt(IDL.Nat),
    'billingPeriod' : IDL.Text,
    'imageAllowance' : IDL.Opt(IDL.Nat),
    'price' : IDL.Nat,
  });
  const Result_6 = IDL.Variant({ 'ok' : Plan, 'err' : PaymentError });
  const Result_12 = IDL.Variant({ 'ok' : IDL.Null, 'err' : ContentError });
  const EnquiryId = IDL.Nat;
  const Result_5 = IDL.Variant({ 'ok' : IDL.Null, 'err' : ListingError });
  const Result_11 = IDL.Variant({ 'ok' : IDL.Null, 'err' : PaymentError });
  const SubscriptionStatus = IDL.Variant({
    'active' : IDL.Null,
    'expired' : IDL.Null,
  });
  const Subscription = IDL.Record({
    'status' : SubscriptionStatus,
    'startedAt' : Timestamp,
    'expiresAt' : Timestamp,
    'planId' : PlanId,
    'billingPeriod' : IDL.Text,
    'renewedAt' : IDL.Opt(Timestamp),
    'price' : IDL.Nat,
    'planName' : IDL.Text,
  });
  const MobileVerification = IDL.Variant({
    'pendingReview' : IDL.Null,
    'notSubmitted' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const EmailVerification = IDL.Variant({
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'unverified' : IDL.Null,
  });
  const Customer = IDL.Record({
    'principal' : CustomerId,
    'blocked' : IDL.Bool,
    'mobileVerification' : MobileVerification,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'whatsapp' : IDL.Text,
    'email' : IDL.Text,
    'updatedAt' : Timestamp,
    'company' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'emailVerification' : EmailVerification,
  });
  const CustomerAccount = IDL.Record({
    'customer' : Customer,
    'subscription' : IDL.Opt(Subscription),
  });
  const Enquiry = IDL.Record({
    'id' : EnquiryId,
    'listingId' : ListingId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'read' : IDL.Bool,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const AdminEnquiry = IDL.Record({
    'listingTitle' : IDL.Text,
    'enquiry' : Enquiry,
  });
  const AdminListingSummary = IDL.Record({
    'listing' : Listing,
    'enquiryCount' : IDL.Nat,
  });
  const AdminPayment = IDL.Record({
    'customerName' : IDL.Text,
    'customerEmail' : IDL.Text,
    'payment' : Payment,
  });
  const CustomerError = IDL.Variant({
    'notAuthorized' : IDL.Null,
    'notFound' : CustomerId,
    'invalidCode' : IDL.Null,
    'alreadyRegistered' : IDL.Null,
    'notRegistered' : IDL.Null,
  });
  const Result = IDL.Variant({ 'ok' : Customer, 'err' : CustomerError });
  const EnquiryAdminError = IDL.Variant({
    'notAuthorized' : IDL.Null,
    'notFound' : EnquiryId,
  });
  const Result_10 = IDL.Variant({ 'ok' : Enquiry, 'err' : EnquiryAdminError });
  const ListingUpdate = IDL.Record({
    'region' : IDL.Opt(IDL.Text),
    'title' : IDL.Opt(IDL.Text),
    'postcode' : IDL.Opt(IDL.Text),
    'country' : IDL.Opt(IDL.Text),
    'propertyType' : IDL.Opt(PropertyType),
    'bedrooms' : IDL.Opt(IDL.Nat),
    'area' : IDL.Opt(IDL.Nat),
    'city' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'listingType' : IDL.Opt(ListingType),
    'currency' : IDL.Opt(IDL.Text),
    'addressLine' : IDL.Opt(IDL.Text),
    'bathrooms' : IDL.Opt(IDL.Nat),
    'price' : IDL.Opt(IDL.Nat),
    'photos' : IDL.Opt(IDL.Vec(Photo)),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result__1 = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const CustomerProfileInput = IDL.Record({
    'name' : IDL.Text,
    'whatsapp' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Result_4 = IDL.Variant({ 'ok' : IDL.Null, 'err' : CustomerError });
  const ListingFilter = IDL.Record({
    'propertyType' : IDL.Opt(PropertyType),
    'minBedrooms' : IDL.Opt(IDL.Nat),
    'maxPrice' : IDL.Opt(IDL.Nat),
    'listingType' : IDL.Opt(ListingType),
    'keyword' : IDL.Opt(IDL.Text),
    'minPrice' : IDL.Opt(IDL.Nat),
    'location' : IDL.Opt(IDL.Text),
  });
  const EnquiryInput = IDL.Record({
    'listingId' : ListingId,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const EnquiryError = IDL.Variant({
    'listingNotPublished' : ListingId,
    'listingNotFound' : ListingId,
  });
  const Result_3 = IDL.Variant({ 'ok' : Enquiry, 'err' : EnquiryError });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result_13], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addMyListingPhotos' : IDL.Func(
        [ListingId, IDL.Vec(Photo)],
        [Result_1],
        [],
      ),
    'adminAddListingPhotos' : IDL.Func(
        [ListingId, IDL.Vec(Photo)],
        [Result_1],
        [],
      ),
    'adminConfirmPayment' : IDL.Func([PaymentId], [Result_2], []),
    'adminCreateBanner' : IDL.Func([BannerInput], [Result_9], []),
    'adminCreateCategory' : IDL.Func([CategoryInput], [Result_8], []),
    'adminCreateChatbotEntry' : IDL.Func([ChatbotEntryInput], [Result_7], []),
    'adminCreateListing' : IDL.Func([ListingInput], [Result_1], []),
    'adminCreatePlan' : IDL.Func([PlanInput], [Result_6], []),
    'adminDeleteBanner' : IDL.Func([BannerId], [Result_12], []),
    'adminDeleteCategory' : IDL.Func([CategoryId], [Result_12], []),
    'adminDeleteChatbotEntry' : IDL.Func([ChatbotEntryId], [Result_12], []),
    'adminDeleteEnquiry' : IDL.Func([EnquiryId], [Result_5], []),
    'adminDeleteListing' : IDL.Func([ListingId], [Result_5], []),
    'adminDeletePlan' : IDL.Func([PlanId], [Result_11], []),
    'adminGetListing' : IDL.Func([ListingId], [IDL.Opt(Listing)], ['query']),
    'adminGetSubscription' : IDL.Func(
        [CustomerId],
        [IDL.Opt(Subscription)],
        ['query'],
      ),
    'adminListBanners' : IDL.Func([], [IDL.Vec(Banner)], ['query']),
    'adminListCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'adminListChatbotEntries' : IDL.Func(
        [],
        [IDL.Vec(ChatbotEntry)],
        ['query'],
      ),
    'adminListCustomers' : IDL.Func([], [IDL.Vec(CustomerAccount)], ['query']),
    'adminListEnquiries' : IDL.Func([], [IDL.Vec(AdminEnquiry)], ['query']),
    'adminListListings' : IDL.Func(
        [],
        [IDL.Vec(AdminListingSummary)],
        ['query'],
      ),
    'adminListPayments' : IDL.Func([], [IDL.Vec(AdminPayment)], ['query']),
    'adminListPlans' : IDL.Func([], [IDL.Vec(Plan)], ['query']),
    'adminRejectPayment' : IDL.Func([PaymentId], [Result_2], []),
    'adminRemoveListingPhoto' : IDL.Func([ListingId, IDL.Nat], [Result_1], []),
    'adminReorderBanner' : IDL.Func([BannerId, IDL.Nat], [Result_9], []),
    'adminSetBannerEnabled' : IDL.Func([BannerId, IDL.Bool], [Result_9], []),
    'adminSetCustomerBlocked' : IDL.Func([CustomerId, IDL.Bool], [Result], []),
    'adminSetEnquiryRead' : IDL.Func([EnquiryId, IDL.Bool], [Result_10], []),
    'adminSetListingBlocked' : IDL.Func([ListingId, IDL.Bool], [Result_1], []),
    'adminSetListingFeatured' : IDL.Func([ListingId, IDL.Bool], [Result_1], []),
    'adminSetListingPublished' : IDL.Func(
        [ListingId, IDL.Bool],
        [Result_1],
        [],
      ),
    'adminSetMobileVerification' : IDL.Func(
        [CustomerId, MobileVerification],
        [Result],
        [],
      ),
    'adminUpdateBanner' : IDL.Func([BannerId, BannerInput], [Result_9], []),
    'adminUpdateCategory' : IDL.Func(
        [CategoryId, CategoryInput],
        [Result_8],
        [],
      ),
    'adminUpdateChatbotEntry' : IDL.Func(
        [ChatbotEntryId, ChatbotEntryInput],
        [Result_7],
        [],
      ),
    'adminUpdateListing' : IDL.Func([ListingId, ListingUpdate], [Result_1], []),
    'adminUpdatePlan' : IDL.Func([PlanId, PlanInput], [Result_6], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'confirmEmailVerification' : IDL.Func([IDL.Text], [Result], []),
    'createMyListing' : IDL.Func([ListingInput], [Result_1], []),
    'deleteMyListing' : IDL.Func([ListingId], [Result_5], []),
    'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getListing' : IDL.Func([ListingId], [IDL.Opt(Listing)], ['query']),
    'getMyAccount' : IDL.Func([], [IDL.Opt(CustomerAccount)], ['query']),
    'getMyListing' : IDL.Func([ListingId], [IDL.Opt(Listing)], ['query']),
    'getMyListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getMyPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getMySubscription' : IDL.Func([], [IDL.Opt(Subscription)], ['query']),
    'getPlan' : IDL.Func([PlanId], [IDL.Opt(Plan)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listBanners' : IDL.Func([], [IDL.Vec(Banner)], ['query']),
    'listCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'listChatbotEntries' : IDL.Func([], [IDL.Vec(ChatbotEntry)], ['query']),
    'listFeaturedListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'listPlans' : IDL.Func([], [IDL.Vec(Plan)], ['query']),
    'listPublishedListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'registerCustomer' : IDL.Func([CustomerProfileInput], [Result], []),
    'removeMyListingPhoto' : IDL.Func([ListingId, IDL.Nat], [Result_1], []),
    'requestEmailVerification' : IDL.Func([IDL.Text], [Result_4], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'searchListings' : IDL.Func([ListingFilter], [IDL.Vec(Listing)], ['query']),
    'submitEnquiry' : IDL.Func([EnquiryInput], [Result_3], []),
    'submitMobileNumber' : IDL.Func([IDL.Text], [Result], []),
    'submitPayment' : IDL.Func([PlanId, IDL.Text], [Result_2], []),
    'updateMyListing' : IDL.Func([ListingId, ListingUpdate], [Result_1], []),
    'updateMyProfile' : IDL.Func([CustomerProfileInput], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };